### PR TITLE
[DNM] testing set_openstack_containers role

### PR DESCRIPTION
**Pull request by raukadah**
Depends-On: https://github.com/openstack-k8s-operators/ci-framework/pull/1581

### CODE REVIEW

**Comment by raukadah** [comment]
recheck

**Comment by raukadah** [comment]
recheck

**Comment by raukadah** [comment]
recheck

**Comment by raukadah** [comment]
recheck

**Comment by raukadah** [comment]
recheck

**Comment by raukadah** [comment]
recheck

**Comment by raukadah** [comment]
Based on my testing: https://review.rdoproject.org/zuul/build/6529248f880f471db0b985458c95773f
Here is the generated script from set_openstack_containers https://logserver.rdoproject.org/11/11/0b2a3ca7af6326bd0e0a2533b8b88d700aa0b859/github-check/eib-crc-podified-edpm-baremetal/6529248/ci-framework-data/artifacts/update_env_vars.sh
```
c get csv -n openstack-operators \
   -l operators.coreos.com/openstack-baremetal-operator.openstack-operators -o=jsonpath='{.items[0]}' \
   | jq '(.spec.install.spec.deployments[0].spec.template.spec.containers[1].env[] | select(.name=="OS_CONTAINER_IMAGE_URL_DEFAULT")) |= (.value="38.102.83.192:5001/edpm-hardened-uefi:0b2a3ca7af6326bd0e0a2533b8b88d700aa0b859")' \
   > /home/zuul/ci-framework-data/artifacts/update_containers_patch.out
```
and update here the container in use
https://logserver.rdoproject.org/11/11/0b2a3ca7af6326bd0e0a2533b8b88d700aa0b859/github-check/eib-crc-podified-edpm-baremetal/6529248/ci-framework-data/logs/edpm/pods/openstack-operators/openstack-baremetal-operator-controller-manager-5c784b6fddhbwgg-describe.txt
```
Environment:
      OS_CONTAINER_IMAGE_URL_DEFAULT:  38.102.83.192:5001/edpm-hardened-uefi:0b2a3ca7af6326bd0e0a2533b8b88d700aa0b859
      AGENT_IMAGE_URL_DEFAULT:         quay.io/openstack-k8s-operators/openstack-baremetal-operator-agent:latest
      APACHE_IMAGE_URL_DEFAULT:        registry.redhat.io/rhel8/httpd-24:latest
      OS_IMAGE_DEFAULT:                edpm-hardened-uefi.qcow2
      OPERATOR_CONDITION_NAME:         openstack-baremetal-operator.v0.0.1
```

**Comment by raukadah** [comment]
recheck

**Comment by raukadah** [comment]
recheck

**Comment by raukadah** [comment]
recheck

**Comment by jpodivin** [comment]
Can we close this?

**Comment by raukadah** [comment]
recheck

**Comment by raukadah** [comment]
recheck

**Comment by raukadah** [comment]
recheck

**Comment by raukadah** [comment]
recheck

**Comment by raukadah** [comment]
recheck

**Comment by raukadah** [comment]
@jpodivin sure, let me close it and open a new one for testing.

**Pull request closed without merging**
