### PR TITLE
edpm-hardened-uefi improvements

### PR DESCRIPTION
**Pull request by steveb**
**README tweaks**
- Don't pip install edpm-image-builder, source the elements from the
  current directory
- Use :Z for the volume mount to extract the image, for correct SELinux
  labelling

**Remove networking specific elements and scripts**
This is part of the effort to align this image with base images of
pre-provisioned nodes.

- iptables removed, handled by edpm-ansible
- 51-enable-network-service, if this is still an issue it needs to be
  handled in edpm-ansible anyway
- openssh UseDNS no, not required in an EDPM environment
- interface names, keep the same behaviour as the base image

**Increase all small volumes to 300MiB**
Recent mkfs.xfs now fails when volumes are smaller that 300MiB
(mkfs.xfs-6.1.0 on Fedora 38)

This change uses 300MiB as the smallest size for the small partitions.

Depends-On: https://github.com/openstack-k8s-operators/ci-framework/pull/324

### CODE REVIEW

**Comment by Sandeepyadav93** [comment]
recheck

**Comment by Sandeepyadav93** [comment]
recheck

**Comment by Sandeepyadav93** [comment]
recheck

**Comment by Sandeepyadav93** [comment]
@steveb 

With depends-On the bmaas job is working correctly:-

https://logserver.rdoproject.org/7/7/7a4e01a428dfc0ec3f31edbe559d4720f62cd964/github-check/eib-crc-podified-edpm-baremetal/ccd5aa6/ci-framework-data/logs/edpm/pods/openstack/edpm-compute-provisionserver-openstackprovisionserver-c6bfknjg9-describe.txt
~~~
 Successfully pulled image "38.102.83.191:5001/edpm-hardened-uefi:7a4e01a428dfc0ec3f31edbe559d4720f62cd964"
~~~

The failure here is real and looks related to this patch, Job failed because we can't ssh to compute node

https://logserver.rdoproject.org/7/7/7a4e01a428dfc0ec3f31edbe559d4720f62cd964/github-check/eib-crc-podified-edpm-baremetal/ccd5aa6/ci-framework-data/logs/edpm/pods/openstack/dataplane-deployment-configure-network-edpm-compute-k4tt6-logs.txt

~~~
TASK [Gathering Facts] *********************************************************
[1;30mtask path: /runner/project/playbook.yaml:3[0m
[1;31mfatal: [edpm-compute-0]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: ssh: connect to host 172.22.0.100 port 22: No route to host", "unreachable": true}[0m
~~~

Compute node got a wrong IP(got .90 not .100):-

~~~
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 52:54:00:5b:9c:de brd ff:ff:ff:ff:ff:ff
    altname enp1s0
    inet 172.22.0.90/24 brd 172.22.0.255 scope global dynamic noprefixroute eth0
       valid_lft 2512sec preferred_lft 2512sec
    inet6 fe80::5054:ff:fe5b:9cde/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
~~~  


the interface name here is now eth0 we use enp1s0

https://github.com/openstack-k8s-operators/dataplane-operator/blob/main/config/samples/dataplane_v1beta1_openstackdataplane_baremetal_with_ipam.yaml#L33

~~~
edpm-compute-0 lib]# less /var/log/cloud-init.log  | grep 172.22
2023-07-02 06:36:08,369 - stages.py[DEBUG]: applying net config names for {'version': 1, 'config': [{'name': 'enp1s0', 'type': 'physical', 'subnets': [{'gateway': '172.22.0.3', 'netmask': '255.255.255.0', 'type': 'static', 'address': '172.22.0.100', 'ipv4': True}], 'mac_address': None}, {'address': ['172.22.0.80'], 'search': ['ctlplane.example.com', 'osptest.openstack.org'], 'type': 'nameserver'}]}
~~~

~~~
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 52:54:00:5b:9c:de brd ff:ff:ff:ff:ff:ff
    altname enp1s0
    inet 172.22.0.90/24 brd 172.22.0.255 scope global dynamic noprefixroute eth0
       valid_lft 2512sec preferred_lft 2512sec
    inet6 fe80::5054:ff:fe5b:9cde/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
~~~  

Looks like removing `stable-interface-names` caused the issue.

**Comment by steveb** [comment]
eib-crc-podified-edpm-baremetal is green, could we merge it please?

https://review.rdoproject.org/zuul/buildset/b189eda3b6844b90adfb53ca669cc7e3

**Review by kajinamit — APPROVED** [review]
/lgtm

**Comment by kajinamit** [comment]
wondering if we want to enable automation to merge PRs according to results posted by CI.

**Comment by steveb** [comment]
> wondering if we want to enable automation to merge PRs according to results posted by CI.

Yeah now that we have eib-crc-podified-edpm-baremetal. Plus requiring a / lgtm

**Pull request merged**
